### ISSUE TITLE
What persistance systems do we have to support for first release?

### ISSUE THREAD

**Issue by tgalopin** [FriendsOfSymfony/FOSMessage#1]
Hello everyone,

One of the questions we have to ask ourselves is what persistance system do we have / want to support for first release?

I think Doctrine ORM and ODM are clearly needed. However, I don't know very well the popularity of the others.

FOSUserBundle supports Propel. Are there a lot of people using Propel?
Does anyone else use another persistance layer and would like a support for it in the library?

**Comment by dbu** [comment]
i would say if the library comes with the base code and just doctrine
ORM support, that is a good start. whoever needs the other storages can
contribute them. if you manage two systems (i assume by ODM you mean the
MongoDB ODM, not the couchdb odm or phpcr-odm), its even better because
it will show whether the models are somehow too closely tied to the ORM
thinking.

**Comment by tgalopin** [comment]
I think I will start with Doctrine ORM yes. I will implement Mongo ODM later and we will see if other persistance systems could be interesting. Thanks @dbu !

**Comment by Miliooo** [comment]
Keep in mind that one of the reasons FOSMessageBundle became stale in updates was that if you wanted to add a feature you had to add it for both drivers or it wouldn't get accepted... It's hard to keep those things in sync.

**Comment by ionafan2** [comment]
If we talk about "for first release" then Abstract layer and one implementation like Doctrine ORM will be enough.

**Comment by stof** [comment]
@tgalopin I'm dreaming of killing the propel 1 support in FOSUserBundle actually. The fact that it requires to extend the Propel base class means I have to duplicate everything for propel support.

Regarding the different Doctrine implementations, the great things is that many code can be shared (you need different implementations only for places where you perform complex queries). And they don't require special entity/document classes (the model class just has a dependency on `doctrine/collections` in case you have toMany relations). What would be needed here is to split the basic persistence responsibility from the complex querying responsibility. This way, the first part can be shared between all doctrine projects.

**Comment by tgalopin** [comment]
@Miliooo That's a very good point. With this and @stof explainations, I think we will go only for Doctrine ORM and Mongo ODM.

@stof Thanks for your feedback. I already planned to make the library depend on `doctrine/collections`. Do you have ideas on how to split the persitance responsability and the querying? I created a `Driver` system in the test library (https://github.com/tgalopin/message), perhaps should it be more eveolved.

**Comment by tgalopin** [comment]
I close this as we made our decision.
