### ISSUE TITLE
Question: when can this be ready to integrate?

### ISSUE THREAD

**Issue by iBasit** [FriendsOfSymfony/FOSMessage#10]
We are creating new app and I would like to add this into it. I know this will take some time before it can be ready, but the question is when will it be?

**Comment by tgalopin** [comment]
On a technical level, the library is ready. The main last step is to write the documentation (I don't have much time to do so right now). You can try to use it if you want, I would love to get feedbacks from people trying it :) .

If I have to set a date for a first beta, I would probably say beginning of december. I am going to have more time starting mid-november, I will start to write doc and finaize the tests.

Stay tuned and thanks for your interest! If you want to give a hand, don't hesitate :) .

**Comment by iBasit** [comment]
I'm very excited to use this for our application, but I think you will finish your doc before we can start using it which will also help with setting up with even dispatchers for email reply messages. 

I would defo contribute here with fixes  and maybe tutorial with some third party usage.

**Comment by tgalopin** [comment]
If you are interested in using a library in development (before the first release) to try to find bugs, I would be happy to write a bit of documentation today and tomorrow and help you to set it up in your project. It would be great to have a feedback of a real usage of the library :) .

In what kind of project do you want to use it?

**Comment by greg606** [comment]
I am also in need of messaging library and considering the new one, but as I see this one is very bare bone - no ui, forms, controller etc. So lots of to add by myself. Am I right?

**Comment by tgalopin** [comment]
You are exactly right: the ui will be provided by framework implementations. However, this library does provide a lot of features you will use in a classical messaging system. You can think of it as useful tools you would use in your controllers.

**Comment by tgalopin** [comment]
I wrote a few pages of documentation: http://fosmessage.readthedocs.org.

It's not finished but it's a start. Don't hesitate to try, the library itself is in my opinion quite stable.

**Comment by MHaendel** [comment]
Sample integration for Symfony would be nice :+1:

**Comment by tgalopin** [comment]
I'll try to so that :) .

**Comment by iBasit** [comment]
Sorry I couldn't message earlier. 

Ya that would be nice. I'm almost ready to start integrating this bundle. just few more stuff left before I can start on it.

Integration will also involve realtime updates on web app and notifications via email

**Comment by bcosynot** [comment]
The docs look pretty great. Would love to see a sample integration with Symfony as mentioned earlier. I am using the earlier FOSMessageBundle in a project I started but wouldn't mind migrating to this.

**Comment by tgalopin** [comment]
I added a bit of documentation for the Symfony integration: http://fosmessage.readthedocs.org/en/latest/book/getting_started.html#configuration-using-symfony

**Comment by radbrad86** [comment]
I noticed that the MessagePerson contains a "read" boolean which gets set for the sender as soon as the message is created... But I am having trouble figuring out how to read the "read" property when the message if received by one of the recipients. Using getMessages($convoID) doesn't seem to return the "read" state for the current user...

Is this something that's still under active development?

**Comment by tgalopin** [comment]
@bjrothman Actually, the `read` property is a DateTime corresponding to the last read of the person from the MessagePerson object (it's not a boolean). But you are right, this is still under development. I'm trying to figure out what would be the best (ie. easy to use and maintain) way to do that :) .

**Comment by radbrad86** [comment]
Thanks for the reply. I have implemented a work around for the mean time. I am using Symfony and manually got the PersonMessage repo and searched for current conversation and current user to see if the message was read or not.

One thing to keep in mind while trying to find the ideal solution: The Conversation object should return a boolean indicating whether there are any unread messages for the current user. This would be useful so that you don't need to iterate over all the messages in each conversation to determine whether a conversation contains unread messages.

**Comment by iBasit** [comment]
Hi @tgalopin,

I'm integrating this bundle while extending entities in my project. 

Question:

Driver only asks for 4 entities, but leaves out two other entities (tags and conversation person tags).

Will it be fine to leave out those entity from driver as they will not be needed to call directly?

```
        FOS\Message\Driver\Doctrine\ORM\DoctrineORMDriver

        $conversationClass = 'FOS\Message\Driver\Doctrine\ORM\Entity\Conversation',
        $conversationPersonClass = 'FOS\Message\Driver\Doctrine\ORM\Entity\ConversationPerson',
        $messageClass = 'FOS\Message\Driver\Doctrine\ORM\Entity\Message',
        $messagePersonClass = 'FOS\Message\Driver\Doctrine\ORM\Entity\MessagePerson'
```

**Comment by tgalopin** [comment]
Hi @iBasit,

The thing is that the driver don't need to be able to create tags: you should be the only one who create them, as a developer. So the driver does not need to know your tag class.

The default proposed Tag entity (`FOS\Message\Driver\Doctrine\ORM\Entity\Tag`) can be used as a simple but usually enough implementation of the TagInterface. If you want to use another one (a more specific one), don't hesitate to extend the `ConversationPerson` class (either the model or the default entity, as you wish) and instead of referencing the default Tag entity, use or own:

``` php
/**
 * @var \FOS\Message\Model\TagInterface[]|\Doctrine\Common\Collections\ArrayCollection
 *
 * @ORM\ManyToMany(targetEntity="Your\Entity\Here")
 * @ORM\JoinTable(name="conversations_persons_tags")
 */
protected $tags;
```

Then in your code, all you have to do is use the tagger:

``` php
// Either create it or load it from the database, but you should always use the same tag object for
// each conversation with the tag 'private'.
$tag = new Tag('private');

$tagger = new Tagger($driver, $repository);
$tagger->addTag($conversation, $user, $tag);
```

**Comment by iBasit** [comment]
Thank you for letting me know that it does not use it, I might just even remove it or might not. (dont need it for this project).

Just one last question.

I want to extend conversation class and add new field on it. field `auction`

On create I need to save auction field on conversation table. Do I have to do it with `eventDispatch` or do I have to extend repository class for that and overwrite `startConversation(...)`?

Also before creating any conversation, I need to check if user already have conversation on this auction already, then use existing conversation else create new one (which is above method).

I'm assuming, I just have to create new repository and link it with conversation, so I can use that for fetching, but on creating, is I'm not sure.

**Comment by tgalopin** [comment]
The event is definitely the best way. However, for the moment, if your `auction` field don't have a default value, you won't be able to do it as the current event is dispatched only after the first flush (so it would fail). I'll add an event this evening so you can do it. In the meantime, you can set your field to a default value (for instance, NULL).

For the check if a conversation already exists, just choose between `startConversation` and `sendMessage` in your controller:

``` php
if ($hasConversationWithAuction) {
    $conversation = ...; // already existing conversation
    $sender->sendMessage($conversation, ...);
} else {
    $conversation = $sender->startConversation(...);
}
```

**Comment by iBasit** [comment]
That would be awesome, thanks

**Comment by tgalopin** [comment]
I did the change, if you update the library you should be able to use the followings events:
- `PRE_PERSIST` is dispatched just before the conversation / message is persisted ;
- `POST_PERSIST` is dispatched right after the conversation / message is persisted and flushed ;

In your case, you probably want to use the `PRE_PERSIST` event. If you are using Symfony, you can declare one of your services as a listener of the event `fos_message.pre_persist` and use the event object to edit the conversation / message :) .

**Comment by iBasit** [comment]
Thank you,

I will defo will give a go and if there was any issue, I will post back. 

Thanks again. :)

**Comment by iBasit** [comment]
I came on a problem. I needed message id for `$sender->startConversation`, but I can only get it in dispatchEvent, if I wanted to get it here, I can't.  for reply message, I can get it for that.

```
// use this for first time.
$conversation = $sender->startConversation($this->getUser(), $to, $message, $subject);

// use this on reply (second message)        
$message = $sender->sendMessage($conversation, $this->getUser(), $message);

```

**2nd. Question**

I'm also confused on how I will pass object inside disptachEvent method.

basically Object or value is created from Route (url) "slug" and that needs to be passed to dispatchEvent. (I don't want to use request->query(), because I want to manually pass it, if it was run from command line)

## Suggestion

When creating new conversation, it should only create conversation and message should be created separately, just like it is doing on reply. Then it will be more flexible.

proposed:

```

if ($id)
    $conversation = $repository->getConversation($id);
else
    $conversation = $respository->createConversation($this->getUser(), $to, $subject); // message removed 

$message = $sender->sendMessage($conversation, $this->getUser(), $message);

```

**Comment by tgalopin** [comment]
I didn't really get your first question.

For the second, would it solves your problem if we dispatched an event between the persist of the conversation and the persist of the message (just after https://github.com/FriendsOfSymfony/FOSMessage/blob/master/src/Sender.php#L92)? I don't like the possibility to create conversations without message, but creating an event in between could let you change the conversation or the message before the first message is persisted.

**Comment by iBasit** [comment]
1st Question. 

I wanted to pass dynamic value (variable or object) to dispatchEvent, which I can't find a way to do it other then putting that value in session (which I'm avoiding to do).

## Solution for above I found

```
/**
     * This will start conversation, but does not save yet, StartMessage will save this model
     *
     * I could have set sender and recipient here, but startMessage is doing same and also takes care of eventDispatcher
     * as well, so its best choice to let startMessage assign sender and recipient.
     */
    public function startNewConversation($subject)
    {
        Assert::nullOrString($subject, '$subject expected either a string or null in Sender::startConversation(). Got: %s');

        // Create conversation and message
        $conversation = $this->createAndPersistConversation($subject);

        return $conversation;
    }

    public function startMessage (ConversationInterface $conversation, PersonInterface $sender, $recipient, $body)
    {
        if (!is_array($recipient) && !$recipient instanceof \Traversable) {
            $recipient = [$recipient];
        }

        Assert::allIsInstanceOf(
            $recipient,
            'FOS\Message\Model\PersonInterface',
            '$recipient expected ether an instance or a collection of PersonInterface in Sender::startConversation().'
        );

        Assert::string($body, '$body expected a string in Sender::startConversation(). Got: %s');

        // Create message
        $message = $this->createAndPersistMessage($conversation, $sender, $body);

        // Add the recipients links
        foreach ($recipient as $person) {
            $this->createAndPersistConversationPerson($conversation, $person);
            $this->createAndPersistMessagePerson($message, $person, false);
        }

        // Add the sender link
        $this->createAndPersistConversationPerson($conversation, $sender);
        $this->createAndPersistMessagePerson($message, $sender, true);

        // Dispatch PRE_PERSIST event
        $event = new ConversationEvent($conversation, $message);

        $this->dispatchEvent(EventDispatcherInterface::PRE_PERSIST, $event);

        $conversation = $event->getConversation();
        $message = $event->getMessage();

        // Persist
        $this->driver->persistConversation($conversation);
        $this->driver->persistMessage($message);
        $this->driver->flush();

        return $message;
    }
```

by returning conversation on first method and message on second method will help do anything we want to after it is run.

**Comment by tgalopin** [comment]
> I wanted to pass dynamic value (variable or object) to dispatchEvent

What do you want to pass? If I do an event in between the persists, you should be able to modify the conversation. Would it be enough?

Can you tell me a bit more about what you're trying to implement? Perhaps is there a better solution to your problem :) .

**Comment by iBasit** [comment]
Example:

In my controller I have generated an Entity.
- ebay item (entity) in controller
- if ebay item exist, then start or pull existing conversation, else throw error
- pass ebay item to conversation table, so it can be stored as foreign key. (so that will help pull conversation for that item)

**Problem**
I can't sent ebay item entity to eventDispatch.

**Comment by tgalopin** [comment]
I'm not sure you are taking the problem in the right sense. In my opinion, here is what should happen:
- you register an event listener listening on FOSMessage PRE_PERSIST event and filtering on ConversationEvent (so you catch only startConversation)
- in your controller, you have the ebay item => you provide this item to your listener, for instance by a setter
- you check if a conversation exists on this ebay item (using a custom repository as the FOSMessage repository can't deal with your entity)
- if it does, you get it using your custom repo, if it doesn't you start one => at this moment, you listener has both the conversation and your item available and can associate them
- FOSMessage persist everything in the database

This way you don't need to extend the Sender, just using the event dispatcher you can do what you want :)

**Comment by iBasit** [comment]
> in your controller, you have the ebay item => you provide this item to your listener, for instance by a setter

Sorry, this question might be silly to you. but how can I transfer ebay item object from controller to listener? by service?

controller:

```
$ebay = $this->get('ebay');
$ebay->load(232);
```

listener
`$ebay = $this->container->get('ebay'); // will this hold the loaded 232 value?
`

If the above example is wrong, then I'm not sure how to provide ebay item to listener from controller. Can you guide on this please.

**Comment by tgalopin** [comment]
Exactly, as a service. Moreover, your listener is a service, you can use it in your controller :) . That's what I would do:

``` php
<?php
$listener = $this->get('ebay.fos_message_listener');
$listener->useItem($ebayItem);

$sender->startConversation(...); // Listener is triggered
```

**Comment by iBasit** [comment]
Interesting solution. 

I like the idea of calling listener and passing value to it  :+1: 

That would solve it. 

Thank you for your prompt feedback.
