### ISSUE TITLE
error when run composer install 

### ISSUE THREAD

**Issue by hero789** [FriendsOfSymfony/FOSMessage#20]
i'm trying to use the FOSMessage with symfony , i've download it and configure it however when trying to run composer install  i got this error 
`[InvalidArgumentException] Bundle "fos_message" does not exist or it is not enabled.`
i know it is not a bundle yet so do i neet to enable in the symfony  appkernel.php ? or what .

**Comment by tgalopin** [comment]
Hello @hero789,

FOSMessage is just a simple library : once you installed it with Composer, no need to install it anywhere else (you don't need to change the AppKernel.php file). You simply need to use the classes provided by the library inside your controllers.

You can check http://fosmessage.readthedocs.org/en/latest/book/getting_started.html#configuration-using-symfony for more details :) .
