### ISSUE TITLE
Would love to help

### ISSUE THREAD

**Issue by Miliooo** [FriendsOfSymfony/FOSMessage#3]
Hey I would love to help with this project. 

I actually rewrote the fos messagebundle once 
https://github.com/Miliooo/MilioooMessageBundle
It actually works but I wrote that code two years ago and I hate most of the code.

Since messaging is a huge part of my project, I started to refactor the code 
https://github.com/Miliooo/MilioMessage

It starts with a command:
https://github.com/Miliooo/MilioMessage/blob/master/src/Commands/CreateThread.php
This gets handled by a handler:
https://github.com/Miliooo/MilioMessage/blob/master/src/Handler/CreateThreadCommandHandler.php
Which then creates a thread model:
https://github.com/Miliooo/MilioMessage/blob/master/src/Model/Thread.php

**Comment by tgalopin** [comment]
Hello @Miliooo !

Thanks for your help proposal, that would be great if you could give a hand!

The first thing you can help us with is the conception of the library. You seem to have a real use-case which is really great as it can be a way to find new ideas.

We worked quite a lot with @ChristianRiesen on how we would like the library to look, and we had some ideas. I implemented them in a personnal repository: https://github.com/tgalopin/message. I planned to use this repository as a basis for this one, but it can change from the feedbacks I have.

The main thing we have to agree on is the external usage. As you have a use-case, I would be very interested by your opinion about the [Usage ideas](https://github.com/FriendsOfSymfony/FOSMessage#usage-ideas) I have in mind. Would it fit your needs?

Do you think you can describe a bit what you will need in your project from the library? What would you like to be able to do with it?

**Comment by Miliooo** [comment]
Hey @tgalopin,

Yeah I saw the code a few hours after I started this thread. 
The readme said that no code has been written, so I thought I would show you my work in progress about creating a message bundle.

Well my use case is actually quite simple, a basic inbox, outbox, archived box messaging system 

### A single thread

![single](https://cloud.githubusercontent.com/assets/3365006/10059517/be2dc924-624b-11e5-93c9-a588f87fef1a.png)

### An inbox folder

![singlethread](https://cloud.githubusercontent.com/assets/3365006/10059521/bfc118cc-624b-11e5-899b-5def0f8b399a.png)

If I look at my use case, and your code, then I have to admit that I have some questions. 

I guess the biggest one would be if you are planning to create an inbox, outbox, archived, deleted box like messaging system. I see some hints about it in the taggers code, but when I think of a tag system, I think about being able to label my gmail messages... You plan to do both with that system?

**Comment by tgalopin** [comment]
You are right, I didn't explain much the ideas I have about the library.

In short, I won't implement any inbox/outbox system. A bit like in Gmail, I just imagined a single list containing all the conversations where the current user is a member. In my opinion, an outbox is not needed: all your conversations will be listed, including the one you started.

I think the tagging system is quite adapted to "archived" conversations.

The plan with this library is to create a simple data structure: no UI, no complex features, etc. Just storing the messages. Then, perhaps the bundle could provide more stuff like validation or templates.

I'll write a bit more what I have in mind for the library in an issue where we will be able to discuss it properly :) .

**Comment by tgalopin** [comment]
@Miliooo I explained and summarize what I have in mind for the library here: https://github.com/FriendsOfSymfony/FOSMessage/issues/5.
