### ISSUE TITLE
not yet implemented error "search message"

### ISSUE THREAD

**Issue by HabibMami** [FriendsOfSymfony/FOSMessage#33]
Hello im a beginner in Symfony 2.8
i installed the FOSMessagebundle i followed the basics all goes great only when i go to search twig
i got a message "not yet implemented "
im i missing anything ?
![image](https://cloud.githubusercontent.com/assets/21245088/17977123/556488f0-6ae8-11e6-8617-a13424f950e3.png)

thank you ! :)

**Comment by tgalopin** [comment]
The search is indeed not implemented in the bundle for the moment. I suggest you develop your own (it's a simple query :) ). The search is not implemented as we would have to support all the possible databases and that's quite difficult.

**Comment by HabibMami** [comment]
ok thank you very much :) and does the bundle provide me readed an unreaded message or number of readed message ??

**Comment by tgalopin** [comment]
Yes it does: you can take a look at the repository (for instance https://github.com/FriendsOfSymfony/FOSMessageBundle/blob/master/EntityManager/ThreadManager.php) to see all the available queries and at the views (for instance https://github.com/FriendsOfSymfony/FOSMessageBundle/blob/master/Resources/views/Message/threads_list.html.twig) to see their usage :) .

**Comment by HabibMami** [comment]
thank you so much :D have nice day !
